image: java:8-jdk

stages:
  - build

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/distributions/*.zip
after_script:
  - echo "End CI"