# This is a basic workflow to help you get started with Actions

name: Plugin Verification

# on:
#   pull_request:
#     branches: [ master, dev ]

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
      
    - name: Build with Gradle
      run: ./gradlew build
  
    - name: Verify Plugin on IntelliJ Platforms
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v0.0.2
      with:
        ide-versions: |
          ideaIC:2019.2
          ideaIC:2019.3
          ideaIC:2020.1
          ideaIC:2020.2
          ideaIC:LATEST-EAP-SNAPSHOT

    - name: Get log file path and print contents
      run: |
        echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}
