# This is a basic workflow to help you get started with Actions

name: Plugin Verification

# on:
#   pull_request:
#     branches: [ master, dev ]

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: submodules-init
      uses: snickerbockers/submodules-init@v4

    - name: Build with Gradle
      run: ./gradlew build

    - name: Verify Plugin on IntelliJ Platforms
      if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      with:
        ide-versions: |
          ideaIC:2021.1
          ideaIC:2021.2
          ideaIC:2021.3
          ideaIC:LATEST-EAP-SNAPSHOT

    - name: Get log file path and print contents
      if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
      run: |
        echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}
