# This is a basic workflow to help you get started with Actions


name: Release

on:
  push
jobs:
  build:
    environment: c200
    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew

#     - name: submodules-init
#       uses: snickerbockers/submodules-init@v4

#     - name: Build with Gradle
#       run: ./gradlew build    
    - name: create-temp
      run: |
        mkdir build
        mkdir build/distributions
        touch build/distributions/PLM Companion-1.0.3.zip
    
    - name: send distribution
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        passphrase : ${{secrets.PASSPHRASE}}
        source: "build/distributions/*"
        target: ${{secrets.REMOTE_TARGET}}
        
    - name: update release
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        passphrase : ${{secrets.PASSPHRASE}}
        script: |
          currentPath = `pwd`
          echo $currentPath
          variable=`printf -- '%s\n' * | awk -F'$currentPath/${{secrets.REMOTE_TARGET}}/PLM Companion-|.zip' '{print $2}'`
          echo $variable
          $currentPath/addNewRelease $variable
      

      
    

